# ==================================================
# SportVerse AI - Training Plan API Routes
# ==================================================
# All responses generated by Gemini LLM via trainer_agent.
# Zero hardcoded text.
# ==================================================

from flask import Blueprint, request, jsonify
from agents.trainer_agent import generate_training_plan, get_coaching_tips

training_bp = Blueprint('training', __name__)


@training_bp.route('/generate-training-plan', methods=['POST'])
def generate_plan():
    """
    Generate a fully personalised AI training plan.

    Body JSON:
      sport, skill_level, goal, additional_info, user_name, duration_weeks
    """
    try:
        data = request.get_json()
        if not data:
            return jsonify({'error': 'No data provided'}), 400

        sport = data.get('sport', 'general')
        skill_level = data.get('skill_level', 'beginner')
        goal = data.get('goal', 'technique')
        additional_info = data.get('additional_info', '')
        user_name = data.get('user_name', 'Athlete')
        duration_weeks = data.get('duration_weeks', 4)

        print(f"📋 Generating training plan for {user_name}: {sport}/{skill_level}/{goal}")

        plan = generate_training_plan(
            sport=sport,
            skill_level=skill_level,
            goal=goal,
            user_name=user_name,
            duration_weeks=int(duration_weeks),
            additional_info=additional_info,
        )

        print(f"✅ Gemini training plan generated for {user_name}")
        return jsonify(plan)

    except Exception as e:
        print(f"❌ Plan generation error: {e}")
        return jsonify({'error': f'Plan generation failed: {str(e)}'}), 500


@training_bp.route('/get-coaching-tips', methods=['POST'])
def coaching_tips():
    """Get focused coaching tips for a specific area."""
    try:
        data = request.get_json()
        sport = data.get('sport', 'general')
        skill_level = data.get('skill_level', 'beginner')
        area = data.get('area', 'general')

        tips = get_coaching_tips(sport, skill_level, area)
        return jsonify(tips)

    except Exception as e:
        return jsonify({'error': str(e)}), 500
